### ISSUE TITLE
Search for dead code (commented out, not used)

### ISSUE THREAD

**Issue by pfrischmuth** [AKSW/Erfurt#136]
- e.g. with https://github.com/sebastianbergmann/phpdcd

**Comment by shinobu** [comment]
this tool https://github.com/sebastianbergmann/phpcpd might proof usefull for refactoring files as well

**Comment by shinobu** [comment]
I've tried using the phpdcd and it throws a bunch of errors, but still gives output (with most likely many false positives). I'm going to check those entries and sort out as many false positives as I can, and afterwards you should recheck the updated list. Any complaints about this @pfrischmuth @white-gecko ? Here is the log for reference:  [phpcdc.txt](https://github.com/AKSW/Erfurt/files/604439/phpcdc.txt)



I've searched for more ways to find dead code, this feature seems to be pretty rare. One other thing i found was https://phpmd.org/ sadly it doesn't search for unused functions right now, but we can find unused variables which is already a useful feature

https://github.com/exakat/php-static-analysis-tools lists a lot of more or less useful tools - maybe one of the analysers actually can list dead code as well. I might look into them prior to going through the logfile from phpdcd

**Comment by k00ni** [comment]
Hi @shinobu, you should exclude the vendor folder in the search, because it only contains foreign software.

**Comment by shinobu** [comment]
@k00ni iirc I ran it in `library/Erfurt' so the vendor folder was ignored

**Comment by k00ni** [comment]
@shinobu: according to your phpcdc.txt file you have lines like:

```
Notice: Undefined index:  in /home/shino/git/Erfurt/vendor/sebastian/phpdcd/src/Analyser.php on line 274
```

According to that line, it checked the vendor folder too (vendor/sebastian).

**Comment by shinobu** [comment]
The undefined index is in the vendor path because `vendor/sebastion/phpdcd` is the program i execute to check the Erfurt Code (as mentioned above) @k00ni

**Comment by k00ni** [comment]
You are right, thanks for the info, my bad.

**Comment by shinobu** [comment]
This is the Log of the phpmd (as mentioned above mostly unused variables)
[phpmd.txt](https://github.com/AKSW/Erfurt/files/611599/phpmd.txt)

**Comment by shinobu** [comment]
Another thing, as phpdcd versions `1.0.0` `1.0.1` `1.0.2/stable Composer Package` all have errors, it would be great if you could check if they run on your setups without errors @pfrischmuth @white-gecko (that shouldn't take longer than 5 minutes)

**Comment by shinobu** [comment]
priorize deleting outcommented code snippets, beware to not delete comments

afterwards go through the phpdcd results

**Comment by white-gecko** [comment]
Commend out code should be done in #140 .
The `phpdcd` is complicated to handle and we don't know, if the result brings much.
The next step should be `phpcpd` and `phpmd`.
