### ISSUE TITLE
SPARQL FILTER regex flags

### ISSUE THREAD

**Issue by martinez099** [AKSW/Erfurt#90]
I use the regex FILTER function to filter my result from SPARQL queries. The 'i' flag works fine, but if I turn the 'm' or the 's' flag on, it behaves strange. The FILTER result is always true, no matter what pattern I use. Are you sure this works correctly?

**Comment by martinez099** [comment]
It seems that if there are newlines in the subject text, the regex FILTER doesn't work after the first newline.

**Comment by white-gecko** [comment]
Are you using the Virtuoso backend? Could you please try to reproduce this behavior with Virtuos directly?

**Comment by martinez099** [comment]
No. I'm using zenddb with mysql as backend.

**Comment by white-gecko** [comment]
The MySQL backend is not feature complete and might have some problems. We recommend using the Virtuoso backend instead.
