### ISSUE TITLE
Parser fails on filter queries with less operand '<'

### ISSUE THREAD

**Issue by BrummbQ** [AKSW/Erfurt#95]
i.e. a query with this filter: `FILTER (?Vertragsbeginn < "2015-01-01")` fails with an Erfurt_Sparql_ParserException

the issue is located at the tokenizer in Sparql/Parser.php. When the loop detects a '<' char, it switches to uri mode and expects an uri, which makes no sense. In that case it must be an operand. On the contrary, the query `FILTER (?Vertragsbeginn > "2015-01-01")` works flawless.

I've no idea why nobody noticed this huge bug in an essential component.

**Comment by white-gecko** [comment]
We've notices this issue already before: https://github.com/AKSW/Erfurt/issues/35 But I didn't find a simple way of fixing this so far.

**Comment by BrummbQ** [comment]
ok, i'll fix it myself then or work around the issue

**Comment by white-gecko** [comment]
Ah cool, we would really look forward to a pull-request to fix this :-)
